#!/usr/bin/env node
/**
 * A5: extract LOCALES from static/i18n.js into src/i18n/strings.json +
 * typed key d.ts. Supports both string-valued entries and function-valued
 * entries (function entries are stored as strings and evaluated at runtime —
 * they never appear as plain interpolatable keys, per vanilla semantics).
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO = path.resolve(__dirname, '..', '..')
const SRC = path.join(REPO, 'static', 'i18n.js')
const OUT_JSON = path.join(REPO, 'static-vite', 'src', 'i18n', 'strings.json')
const OUT_KEYS = path.join(REPO, 'static-vite', 'src', 'i18n', 'keys.d.ts')

function extractLocalesJs(src) {
  // LOCALES is defined as `const LOCALES = { … }` followed by `let _locale = …`.
  // Extract that block precisely without executing the rest of the file.
  const start = src.indexOf('const LOCALES =')
  if (start === -1) throw new Error('no const LOCALES = in i18n.js')
  const end = src.indexOf('\nlet _locale', start)
  if (end === -1) throw new Error('no let _locale sentinel in i18n.js')
  return src.slice(start, end).trim()
}

function loadLocales() {
  const src = fs.readFileSync(SRC, 'utf8')
  const code = extractLocalesJs(src) + '\nLOCALES'
  const locales = vm.runInNewContext(code, { console: { log() {} } })
  return locales
}

function main() {
  const locales = loadLocales()

  // Persist: write JSON per-locale and type declaration.
  const stringified = JSON.stringify(locales, (_k, v) => (typeof v === 'function' ? String(v) : v), 2)
  fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true })
  fs.writeFileSync(OUT_JSON, stringified + '\n', 'utf8')

  const keys = Object.keys(locales.en ?? locales[Object.keys(locales)[0]])
  const keysUnion = keys.map((k) => `  | ${JSON.stringify(k)}`).join('\n')
  const decl =
    '/* GENERATED by scripts/convert-i18n.mjs — do not hand-edit. */\n' +
    'export type I18nKey =\n' + keysUnion + ';\n' +
    'export type I18nLocale = ' + Object.keys(locales).map((l) => JSON.stringify(l)).join(' | ') + ';\n'
  fs.writeFileSync(OUT_KEYS, decl, 'utf8')

  console.log(`wrote ${Object.keys(locales).length} locales, ${keys.length} keys -> ${path.relative(REPO, OUT_JSON)}`)
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main()
