import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')          // static-vite/
const REPO = path.resolve(ROOT, '..')               // repo root
const VANILLA_CSS = path.join(REPO, 'static', 'style.css')
const OUTPUT = path.join(ROOT, 'src', 'styles', 'tokens.css')

/**
 * Mechanical extractor (A2): emit every token-bearing rule from
 * static/style.css verbatim into src/styles/tokens.css.
 *
 * Verbatim contract: bytes inside each emitted rule are NOT rewritten,
 * reformatted, or reordered. The test suite (tests/tokens.test.ts)
 * re-extracts independently and diffs against this file — any hand-edit
 * to tokens.css fails the gate.
 *
 * Emitted rule set (the "token region"):
 *   - the leading global reset (`*, *::before…`) + typography contract comments
 *   - every `:root … { … }` rule (incl. .dark, [data-skin], [data-font-size],
 *     and multi-line blocks) up to the first non-:root top-level rule
 *   - `button,input,select,textarea{…}` font reset that directly follows :root
 */

const READ_LIMIT = 4_000_000 // style.css is ~530 KB; hard stop well above

function sliceTokenRegion(src) {
  // The token region is line-bounded: from the top of the file until the
  // first rule that targets anything other than :root / html-level setup.
  // In static/style.css that boundary is the `.app-*` layout rules that
  // follow the last :root[data-skin] block.
  const endMarkers = [
    '\n  .app-titlebar',      // first chrome rule after skins in current file
    '\n.app-titlebar',
    '\n  .layout',
    '\n.layout',
  ]
  let end = src.length
  for (const marker of endMarkers) {
    const idx = src.indexOf(marker)
    if (idx !== -1 && idx < end) end = idx
  }
  return src.slice(0, end)
}

export function extractTokens(src = fs.readFileSync(VANILLA_CSS, 'utf8')) {
  const region = sliceTokenRegion(src)
  const header =
    '/* GENERATED by scripts/extract-tokens.mjs — DO NOT HAND-EDIT. */\n' +
    '/* Verbatim token region of ../../static/style.css. Regenerate with   */\n' +
    '/* `npm run gen:tokens` from static-vite/. Visual parity depends on   */\n' +
    '/* this file staying byte-identical to the extraction.                */\n\n'
  return header + region.replace(/\s+$/, '\n')
}

function main() {
  const src = fs.readFileSync(VANILLA_CSS, 'utf8').slice(0, READ_LIMIT)
  const tokens = extractTokens(src)
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true })
  const prev = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : ''
  // Idempotency guard: header may change wording; compare body only.
  const bodyOf = (s) => s.replace(/^\/\* GENERATED[\s\S]*?\*\/\n\n/, '')
  if (prev && bodyOf(prev) === bodyOf(tokens)) {
    console.log('tokens.css already up to date')
    return
  }
  fs.writeFileSync(OUTPUT, tokens, 'utf8')
  console.log(`wrote ${tokens.length} bytes -> ${path.relative(REPO, OUTPUT)}`)
}

const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)

if (invokedDirectly) main()
