# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import importlib.util
import pathlib as _pathlib
import sys
_spec = importlib.util.spec_from_file_location('agent_pb2', str(_pathlib.Path(__file__).with_name('agent_pb2.py')))
_mod = importlib.util.module_from_spec(_spec)
sys.modules['agent_pb2'] = _mod
assert _spec and _spec.loader
_spec.loader.exec_module(_mod)
agent__pb2 = _mod

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/hermes.agent.v1.Agent/Ping',
                request_serializer=agent__pb2.PingRequest.SerializeToString,
                response_deserializer=agent__pb2.PingResponse.FromString,
                _registered_method=True)
        self.RunTurn = channel.unary_stream(
                '/hermes.agent.v1.Agent/RunTurn',
                request_serializer=agent__pb2.RunTurnRequest.SerializeToString,
                response_deserializer=agent__pb2.TurnEvent.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/hermes.agent.v1.Agent/Cancel',
                request_serializer=agent__pb2.CancelRequest.SerializeToString,
                response_deserializer=agent__pb2.CancelResponse.FromString,
                _registered_method=True)


class AgentServicer:
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=agent__pb2.PingRequest.FromString,
                    response_serializer=agent__pb2.PingResponse.SerializeToString,
            ),
            'RunTurn': grpc.unary_stream_rpc_method_handler(
                    servicer.RunTurn,
                    request_deserializer=agent__pb2.RunTurnRequest.FromString,
                    response_serializer=agent__pb2.TurnEvent.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=agent__pb2.CancelRequest.FromString,
                    response_serializer=agent__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hermes.agent.v1.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hermes.agent.v1.Agent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Agent:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.agent.v1.Agent/Ping',
            agent__pb2.PingRequest.SerializeToString,
            agent__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hermes.agent.v1.Agent/RunTurn',
            agent__pb2.RunTurnRequest.SerializeToString,
            agent__pb2.TurnEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.agent.v1.Agent/Cancel',
            agent__pb2.CancelRequest.SerializeToString,
            agent__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
