# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
_runtime_version.ValidateProtobufRuntimeVersion = lambda *a, **kw: None  # patched: gencode 7.35 vs runtime 6.33
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x0fhermes.agent.v1\"\r\n\x0bPingRequest\"\x1f\n\x0cPingResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\"\xa5\x01\n\x0eRunTurnRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\tworkspace\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x10\n\x08provider\x18\x06 \x01(\t\x12\x14\n\x0chistory_json\x18\x07 \x01(\t\x12\x13\n\x0b\x61ttachments\x18\x08 \x03(\t\"h\n\tTurnEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07preview\x18\x04 \x01(\t\x12\x11\n\tdata_json\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"#\n\rCancelRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x10\n\x0e\x43\x61ncelResponse2\xe1\x01\n\x05\x41gent\x12\x43\n\x04Ping\x12\x1c.hermes.agent.v1.PingRequest\x1a\x1d.hermes.agent.v1.PingResponse\x12H\n\x07RunTurn\x12\x1f.hermes.agent.v1.RunTurnRequest\x1a\x1a.hermes.agent.v1.TurnEvent0\x01\x12I\n\x06\x43\x61ncel\x12\x1e.hermes.agent.v1.CancelRequest\x1a\x1f.hermes.agent.v1.CancelResponseB(Z&hermes-web-go/internal/agentpb;agentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&hermes-web-go/internal/agentpb;agentpb'
  _globals['_PINGREQUEST']._serialized_start=32
  _globals['_PINGREQUEST']._serialized_end=45
  _globals['_PINGRESPONSE']._serialized_start=47
  _globals['_PINGRESPONSE']._serialized_end=78
  _globals['_RUNTURNREQUEST']._serialized_start=81
  _globals['_RUNTURNREQUEST']._serialized_end=246
  _globals['_TURNEVENT']._serialized_start=248
  _globals['_TURNEVENT']._serialized_end=352
  _globals['_CANCELREQUEST']._serialized_start=354
  _globals['_CANCELREQUEST']._serialized_end=389
  _globals['_CANCELRESPONSE']._serialized_start=391
  _globals['_CANCELRESPONSE']._serialized_end=407
  _globals['_AGENT']._serialized_start=410
  _globals['_AGENT']._serialized_end=635
# @@protoc_insertion_point(module_scope)
